version: '3.8'

services:
  selenium-execution-engine:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./screenshots:/tmp/screenshots
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/selenium/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
